### ISSUE TITLE
Parsing the ICD-10-PCS codes from Excel into JSON

### ISSUE THREAD

**Issue by mubassirhayat** [codeforpakistan/HCAIs-Surveillance-Backend#1]
Create and save JSON objects of all data from the sheet "ALL 2022 ICD-10-PCS CODES" in the shared excel file.

**Comment by mubassirhayat** [comment]
First add the ICD10 Equivalent code and then parse the whole sheet

**Comment by bushramustafa** [comment]
Just enter the ICD-10 codes. Enter the codes along with procedure name. Search on the basis of both. Include multiple selection as well.

**Comment by bushramustafa** [comment]
[https://docs.google.com/spreadsheets/d/1JlNXmlUtGO8Fs8bY-iLSaZgM2FVDfGmOBZz5ZV5_J44/edit?usp=sharing](url)

**Comment by bushramustafa** [comment]
[https://docs.google.com/spreadsheets/d/169rnJVPSOIVTgHbyYkyNnxluWBXZAm30Jzo7wtOCVnY/edit?usp=sharing](url)

**Comment by mubassirhayat** [comment]
@HammadAli55 can you please parse the codes from the docs to the mongo collection?
